### ISSUE TITLE
Support for concatenation (`Base.:*`)

### ISSUE THREAD

**Issue by XQP-Munich** [stevengj/LaTeXStrings.jl#54] opened 2021-10-14 13:40 UTC
Currently, the concatenation of two `LaTeXString`s using the operator `*` yields a `String`, not a `LaTeXString`.

I propose to overload `Base.:*`, to the effect of something like

```julia
function Base.:*(lhs::LaTeXString, rhs::LaTeXString)
	return LaTeXString(lhs.s[1:end-1]*rhs.s[2:end])
end
```

Note that this example is not a valid implementation, since  `LaTeXString`s do not need to start and end with `$`, for example when they contain text.

**Comment by stevengj** [comment] 2021-11-03 13:11
Duplicate of #17.

**Closed by stevengj** 2021-11-03 13:11 UTC
